### ISSUE TITLE
being blind messes up noportal/norecall reference position

### ISSUE THREAD

**Issue by fiendish** [fiendish/aardwolfclientpackage#187]
_From [Fiendi...@gmail.com](https://code.google.com/u/103594094024149722366/) on November 17, 2012 01:13:56_

reported by Nuanse
# 

Blind flag should remove mapper ability

if you do: 
->get blinded
enter aardhotel
heal blind
enter portal

-> it makes room you were blinded no_portal

aff_blind should make mapper to disable noportal flag addition until cured.

_Original issue: http://code.google.com/p/aardwolfclientpackage/issues/detail?id=187_

**Comment by fiendish** [comment]
_From [Fiendi...@gmail.com](https://code.google.com/u/103594094024149722366/) on November 24, 2012 10:17:05_

should be fixed @ r1710

**Status:** Fixed

**Comment by madcatz1999** [comment]
As far as I can tell by looking at the code (and from reports from other players), this wasn't fixed.  Looks (to me) like the mapper checks for blindness upon hitting noportal/norecall.  The above bug happens if you cure blind _before_ hitting noportal/norecall.
Edit: Maybe have the mapper look up the room id again before adding noportal/norecall flag?  Should keep you from doing the whole "check for blindness" thing.  Though I probably haven't thought this through.
Or maybe have the mapper catch the "You can't see anything!" line, and stop assuming the player is in a certain room until they get another room gmcp.  Although I guess that would screw up players actually being able to use the mapper to accurately navigate while blind.

**Comment by madcatz1999** [comment]
Also note that many people actually like that this bug exists, as it allows them to manually set a room noportal/norecall.  Perhaps a way to do that manually without exploiting this bug would appease them.

**Comment by fiendish** [comment]
related to #212

**Comment by fiendish** [comment]
please try https://raw.githubusercontent.com/fiendish/aardwolfclientpackage/40df20b287e87cc42dc341288011c81586516a2d/MUSHclient/worlds/plugins/aard_GMCP_mapper.xml
